[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | venv
  | \.git
  | __pycache__
  | \.env
  | \.example
  | README\.md
  | requirements\.txt
)/
'''